# Generated by Django 5.0 on 2024-03-14 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_login_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(upload_to='')),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('batch_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('mentor', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_attendance', models.PositiveIntegerField()),
                ('weekly_tests_score', models.PositiveIntegerField()),
                ('mock_interview_performance', models.PositiveIntegerField()),
                ('placement_interviews', models.PositiveIntegerField()),
                ('drawbacks', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_page.studentprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='student_login',
        ),
    ]
