# Generated by Django 5.0 on 2024-03-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_studentprofile_studentperformance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('doj', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('photograph', models.ImageField(upload_to='documents')),
                ('father_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('passed_out_year', models.PositiveSmallIntegerField()),
                ('stream', models.CharField(choices=[('python_full_stack', 'Python Full Stack'), ('java_full_stack', 'Java Full Stack'), ('testing', 'Testing'), ('devops', 'DevOps'), ('other', 'Other')], max_length=20)),
                ('course_type', models.CharField(choices=[('degree', 'Degree'), ('b.tech', 'B.Tech'), ('mca', 'MCA'), ('other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('other', 'Other')], max_length=5)),
                ('graduation_type', models.CharField(choices=[('degree', 'Degree'), ('b.tech', 'B.Tech'), ('mca', 'MCA'), ('other', 'Other')], max_length=20)),
                ('username', models.CharField(blank=True, max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_pic',
        ),
    ]
