# Generated by Django 5.0 on 2024-03-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0004_student_remove_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_type',
            field=models.CharField(choices=[('python_full_stack', 'Python Full Stack'), ('java_full_stack', 'Java Full Stack'), ('testing', 'Testing'), ('devops', 'DevOps'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='photograph',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('IT', 'IT'), ('CIVIL', 'CIVIL'), ('MECHANICAL', 'MECHANICAL'), ('EEE', 'EEE'), ('DS', 'DS'), ('other', 'Other')], max_length=20),
        ),
    ]
