# Generated by Django 5.0 on 2024-03-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0005_alter_student_course_type_alter_student_photograph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photograph',
        ),
    ]
